CREATE TABLE [dbo].[clients] (
    [id]                   VARCHAR (9)    NOT NULL,
    [firstName]            VARCHAR (100)  NOT NULL,
    [lastName]             VARCHAR (100)  NOT NULL,
    [email]                VARCHAR (150)  NOT NULL,
    [phoneNumber]          VARCHAR (MAX)  NULL,
    [cellPhoneNumber]      VARCHAR (MAX)  NULL,
    [address]              VARCHAR (MAX)  NULL,
    [birthDate]            DATETIME2 (5)  NOT NULL,
    [firstShot]            DATETIME2 (5) NOT NULL,
    [secondShot]           DATETIME2 (5) NOT NULL,
    [thirdShot]            DATETIME2 (5) NOT NULL,
    [fourthShot]           DATETIME2 (5) NOT NULL,
    [vaccine1Manufacturer] NVARCHAR (MAX) NOT NULL,
    [vaccine2Manufacturer] NVARCHAR (MAX) NOT NULL,
    [vaccine3Manufacturer] NVARCHAR (MAX) NOT NULL,
    [vaccine4Manufacturer] NVARCHAR (MAX) NOT NULL,
    [positiveDate]         DATETIME2  (5) NOT NULL,
    [coronaRecovery]       DATETIME2  (5) NOT NULL,
    [created_at]           DATETIME       DEFAULT (getdate()) NOT NULL,
    PRIMARY KEY CLUSTERED ([id] ASC),
    UNIQUE NONCLUSTERED ([email] ASC));